# modules/config.py

from project_paths import project_path

MODEL_OBB_PATH = project_path("model/yolo/best-obb-yolo11m-head_tail.pt")
MODEL_HBB_3FRAME_PATH = project_path("model/best-hbb-3frame.pt")

IMGSZ_OBB = 960
IMGSZ_HBB = 416
HBB_CONF = 0.30
HBB_TEMPORAL_FRAMES = 3
HBB_TEMPORAL_STEP_FRAMES = 10

DEFAULT_SKIP_FRAMES = 10
DEFAULT_TOTAL_SHRIMP = 6
DEFAULT_KEYFRAMES = 12
DEFAULT_TIME_WINDOW_SEC = 10

ID_MATCH_DISTANCE = 260
VOTE_WINDOW_SECONDS = 10.0
MALE_LINE_MISSING_GRACE_SECONDS = 1.0
OBS_RATE_MIN = 0.25
MALE_RATE_THRESHOLD = 0.50
MIN_OBSERVATIONS_PER_SHRIMP = 3
RELIABLE_FORCED_ID_RATE = 35
