# modules/config.py

MODEL_OBB_PATH = "model/yolo/best-obb-yolo11m.pt"
MODEL_HBB_PATH = "model/yolo/best-hbb-yolo11m.pt"
MODEL_CNN_PATH = "model/cnn/best_resnet18_gray.pt"
MODEL_HEAD_TAIL_OBB_PATH = "model/yolo/best-obb-yolo11m-head_tail.pt"
MODEL_SEX_CNN_PATH = "model/cnn/best_resnet18-head_tail.pt"
MODEL_SEX_YOLO_CLS_PATH = "model/yolo/best-cls-yolo11m.pt"
MODEL_SEX_CLASSIFIER_PATH = MODEL_SEX_CNN_PATH

IMGSZ_OBB = 640
IMGSZ_HBB = 416
HBB_CONF = 0.0
CNN_MALE_LINE_THRESHOLD = 0.7

DEFAULT_SKIP_FRAMES = 10
DEFAULT_TOTAL_SHRIMP = 6
DEFAULT_KEYFRAMES = 12
DEFAULT_TIME_WINDOW_SEC = 10

ID_MATCH_DISTANCE = 260
VOTE_WINDOW_SECONDS = 10.0
MALE_LINE_MISSING_GRACE_SECONDS = 2.0
OBS_RATE_MIN = 0.03629
MALE_RATE_THRESHOLD = 0.93327
MIN_OBSERVATIONS_PER_SHRIMP = 3
RELIABLE_FORCED_ID_RATE = 35
